replicaCount: 1

app:
  replica: 3
  image: traefik/whoami
  tag: latest
  env:
    - name: SERVICE_TOKEN
      value: some-service-token-from-BE
    - name: PUBLIC_URL
      value: http://www.example.com
    - name: DB_URL
      value: jdbc:postgresql://postgres-service:5432/recording
    - name: DB_USER
      value: recording
    - name: DB_PASSWORD
      value: recording
    - name: APPENDER_TYPE
      value: json-console
  deployPorts:
    - containerPort: 80 # application port
  servicePorts:
    - name: port1
      # public to the nginx
      # the app.service is a LoadBalancer
      # so we can use the nginx with ssl to proxy this port
      port: 8080
      # the [deployPorts: containerPort] port
      targetPort: 80

postgres:
  env:
    - name: POSTGRES_USER
      value: recording
    - name: POSTGRES_PASSWORD
      value: recording
    - name: POSTGRES_DB
      value: recording
  dataPath: /home/postgres-data
  nodeSelector:
    kubernetes.io/hostname: k3s # node-name

elasticsearch:
  dataPath: /home/elasticsearch-data # chmod 777 /home/elasticsearch-data
  nodeSelector:
    kubernetes.io/hostname: k3s # node-name
